spring:
  application:
    name: order-system
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.100:8848
        username: nacos
        password: nacos
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.2.100:3306/messi_order_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  redis:
    host: 192.168.2.100
    port: 6379
    password: 123456

server:
  port: 8084

dubbo:
  scan:
    # 指定扫描的位置
    base-packages: com.messi.system.order.api
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: 28084
  consumer:
    check: false
    # 订阅指定的服务
  cloud:
    subscribed-services: user-system,product-system,market-system

mybatis-plus:
  configuration:
    # 开启控制台打印SQL
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 指定mapper.xml在resources目录的位置
  mapper-locations: classpath:mapper/*.xml

#seata配置
seata:
  tx-service-group: tx-order-group
  service:
    grouplist:
      order-seata: 192.168.2.100:8091
    vgroup-mapping:
      tx-order-group: order-seata

rocketmq:
  name-server: 192.168.2.100:9876

#xxljob
xxl:
  job:
    admin:
      address: http://192.168.2.100:8079/xxl-job-admin
    executor:
      name: order-system-xxl-job

#elasticsearch配置
elasticsearch:
  node: 192.168.2.100:9300
  shards-number: 1
  replicas-number: 1
  request-max-return-number: 10000